tftf*.exp: Add failure clauses for fail-fast
Similar to other recent update to LAVA exp files, to avoid hanging until
timeout in case of obvious failures.

Seen at https://tf.validation.linaro.org/scheduler/job/1675499:

Waiting for 'Booting trusted firmware test framework'
NOTICE:  BL31: v2.9(release):v2.9.0-169-gc219b03df
NOTICE:  BL31: Built : 12:55:40, Jun 14 2023
INFO: Initializing Hafnium (SPMC)
INFO: text: 0x6000000 - 0x6029000
INFO: rodata: 0x6029000 - 0x6030000
INFO: data: 0x6030000 - 0x6119000
INFO: stacks: 0x6120000 - 0x6130000
INFO: Supported bits in physical address: 40
INFO: Stage 2 has 3 page table levels with 2 pages at the root.
INFO: Stage 1 has 4 page table levels with 1 pages at the root.
INFO: Memory range:  0xfd000000 - 0xfeffffff
INFO: Memory range:  0x7000000 - 0x7ffffff
INFO: Memory range:  0xff000000 - 0xffffffff
ERROR: Boot order must be a unique value.ERROR: Error parsing partition manifest: Boot order should be a unique value less than default largest value.
Panic: Could not parse manifest: Boot order should be a unique value less than default largest value.

Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>
Change-Id: I0864dc25fe29d4af37bc336ecbe58411ed24caf7
(cherry picked from commit 8612170512c2060b0a9d4960c9769053f4c4e593)